<head><title>Covid-19 Data</title></head>

<body>
<?php
include 'open.php';

	//Override the PHP configuration file to display all errors
	   //This is useful during development but generally disabled before release
       ini_set('error_reporting', E_ALL);
			   ini_set('display_errors', true);

     if ($stmt = $conn->prepare(
      "with Rate as ".
      "(select country_name, max(deaths/population) as rate ".
      "from Global) ".
      "select G.country_name, G.date_, (G.deaths/G.population) as death_population_rate ".
      "from Global as G, Rate as R ".
      "where (G.deaths/G.population) = R.rate ".
      "group by country_name;")) {

      //Attach the ? in prepared statements to variables (even if those variables
      //don't hold the values we want yet).  First parameter is a list of types of
      //the variables that follow: 's' means string, 'i' means integer, 'd' means
      //double. E.g., for a statment with 3 ?'s, where middle parameter is an integer
      //and the other two are strings, the first argument included should be "sis".
     // $stmt->bind_param("s", $item);

      //Run the actual query
      if ($stmt->execute()) {

         //Store result set generated by the prepared statement
         $result = $stmt->get_result();

         if (($result) && ($result->num_rows != 0)) {
	 
            //Create table to display results
	    echo "<h2>Country with the highest death/population rate globally: </h2>";
            echo "<table border=\"1px solid black\">";
            echo "<tr><th> Country Name </th> <th> Year-Month-date </th><th> Fatality-Population Ratio </th></tr>";

            //Report result set by visiting each row in it
            while ($row = $result->fetch_row()) {
               echo "<tr>";
               echo "<td>".$row[0]."</td>";
               echo "<td>".$row[1]."</td>";
               echo "<td>".$row[2]."</td>";
               echo "</tr>";
            } 
         
	 
            echo "</table>";
            //store data into a 
      	    echo "<br><br>";
	    echo "<div>The ratio is calculated by dividing death count by population for each country on each time unit.</div>";
	    echo "<div>If on two distinct days the same country has the same rate, we take the entry with the earliest date.</div>";
	    echo "<div>Then we select the entry with maximum rate.</div>";

         }	else {
         //if ($result->num_rows == 0) {
            //Result contains no rows at all
            echo "No state with the specified name";

		 }

         //We are done with the result set returned above, so free it
         $result->free_result();
      
      } else {

         //Call to execute failed, e.g. because server is no longer reachable,
	 //or because supplied values are of the wrong type
         echo "Execute failed.<br>";
      }

      //Close down the prepared statement
      $stmt->close();

   } else {

       //A problem occurred when preparing the statement; check for syntax errors
       //and misspelled attribute names in the statement string.
      echo "Prepare failed.<br>";
      $error = $conn->errno . ' ' . $conn->error;
      echo $error; 
   }
?>
</body>