<head><title>Covid-19 Data</title></head>

<body>
<?php
include 'open.php';

	//Override the PHP configuration file to display all errors
	   //This is useful during development but generally disabled before release
       ini_set('error_reporting', E_ALL);
			   ini_set('display_errors', true);

     if ($stmt = $conn->prepare(
      "With max_var as ".
      "(select V.variant AS var, max(V.number_sequenced) as max_num ".
      "from Euro_variant AS V) ".
      "select V1.country, V1.year_week, V1.variant, V1.number_sequenced ".
      "from Euro_variant AS V1, max_var ".
      "where V1.variant = max_var.var AND V1.number_sequenced = max_var.max_num;")) {

      //Attach the ? in prepared statements to variables (even if those variables
      //don't hold the values we want yet).  First parameter is a list of types of
      //the variables that follow: 's' means string, 'i' means integer, 'd' means
      //double. E.g., for a statment with 3 ?'s, where middle parameter is an integer
      //and the other two are strings, the first argument included should be "sis".
     // $stmt->bind_param("s", $item);

      //Run the actual query
      if ($stmt->execute()) {

         //Store result set generated by the prepared statement
         $result = $stmt->get_result();

         if (($result) && ($result->num_rows != 0)) {
	 
            //Create table to display results
	    echo "<h2>The Most Pervasive Variant in Europe </h2>";
            echo "<table border=\"1px solid black\">";
            echo "<tr><th> Country Name </th> <th> Year-Month-date </th><th> Variant </th><th> Number of Cases </th></tr>";

            //Report result set by visiting each row in it
            while ($row = $result->fetch_row()) {
               echo "<tr>";
               echo "<td>".$row[0]."</td>";
               echo "<td>".$row[1]."</td>";
               echo "<td>".$row[2]."</td>";
               echo "<td>".$row[3]."</td>";
               
               echo "</tr>";
            } 
         
	 
            echo "</table>";
            //store data into a 
      	    echo "<br><br>";
	    echo "<div>The table finds the variant with the maximum number of cases.</div>";
	    echo "<div>The cases for each variance is collected separately in the data source</div>";

         }	else {
         //if ($result->num_rows == 0) {
            //Result contains no rows at all
            echo "No state with the specified name";

		 }

         //We are done with the result set returned above, so free it
         $result->free_result();
      
      } else {

         //Call to execute failed, e.g. because server is no longer reachable,
	 //or because supplied values are of the wrong type
         echo "Execute failed.<br>";
      }

      //Close down the prepared statement
      $stmt->close();

   } else {

       //A problem occurred when preparing the statement; check for syntax errors
       //and misspelled attribute names in the statement string.
      echo "Prepare failed.<br>";
      $error = $conn->errno . ' ' . $conn->error;
      echo $error; 
   }
?>
</body>