
<head><title>PHP PreparedStatement example</title></head>
<body>

<?php

include 'open.php';

//Override the PHP configuration file to display all errors
//This is useful during development but generally disabled before release
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

//Define a PHP helper function to create a table, given a result set
//with the four columns itemID, sellerNum, category, startPrice
function displayItems($res) {

      if ($res->num_rows == 0) {

         //Result contains no rows at all
         echo "No items found meeting specified criteria";

      } else {
     
         //Create table to display results
         echo "<table border=\"1px solid black\">";
         echo "<tr><th> State Name </th> <th> Date Reached 50% Vaccination</th> ";
         echo "<th> Percent Vaccination </th></tr>";

         //Report result set by visiting each row in it and accessing
	 //attribute values by name of attribute rather than position.
	 //The fetch_assoc returns null when no more rows to fetch.
         while (null !== ($row = $res->fetch_assoc())) {
            echo "<tr>";
            echo "<td>".$row['name']."</td>";
            echo "<td>".$row['date']."</td>";
            echo "<td>".$row['fullyVaccedPercent']."</td>";
            echo "</tr>";
         }

         echo "</table>";
      }
}


//Prepare a statement that we can later execute. The ?'s are placeholders for
//parameters whose values we will set before we run the query
if ($stmt = $conn->prepare(
      "WITH temp AS (SELECT location, MIN(fullyVaccedPercent) AS min_vacced ".
      "FROM State_vaccines ".
      "WHERE fullyVaccedPercent > 50 ".
      "GROUP BY location) ".

      ",temp2 AS (SELECT V.location, V.date, V.fullyVaccedPercent ".
      "FROM temp AS T JOIN State_vaccines AS V ON T.location = V.location AND T.min_vacced = V.fullyVaccedPercent ".
      "GROUP BY V.location, V.date) ".

      "SELECT S.name, T.date, T.fullyVaccedPercent ".
      "FROM States AS S RIGHT OUTER JOIN temp2 AS T ON S.abv = T.location ".
       "WHERE S.name IS NOT NULL ".
       "GROUP BY S.name, T.date ".
       "ORDER BY S.name, T.date;")) {
    

   //Attach the ? in prepared statements to variables (even though those variables
   //don't hold the values we want yet).  First parameter is a list of types of
   //the variables that follow: 's' means string, 'i' means integer, 'd' means
   //double. E.g., for a statment with 3 ?'s, where middle parameter is an integer
   //and the other two are strings, the first argument included should be "sis".


   echo "<h2>Date when Each State Reached 50 Percent Vaccination</h2>";

   
   if ($stmt->execute()) {

      //echo "Finding the last day each state had cumulative cases under 10K ... <br>";

      //Store result set generated by the prepared statement
      $result = $stmt->get_result();

      //Call function defined above to create html output
      displayItems($result);
 
      //We are done with the result set returned above, so free it
      //before we try to call prepared statement again
      $result->free_result();
      
   } else {
      echo "First execute failed.<br>";
   }

   //Output some blank space
   echo "<br><br>";
   //Close down the prepared statement
   $stmt->close();

} else {

    //A problem occurred when preparing the statement; check for syntax errors
    //and misspelled attribute names in the statement string.
    $error = $conn->errno . ' ' . $conn->error;
    echo $error; 
}


//Close the connection created in open.php
$conn->close();
?>
</body>
